msg = input('Digite algo: ')
print('O tipo da variavel é ',type(msg))
print('É alfanumérico ? ',msg.isalnum())
print('É tudo letra ? ',msg.isalpha())
print('É ASCII? ',msg.isascii())
print('É maiúsculo ? ',msg.isupper())
print('É um título ? ',msg.istitle())
print('É espaço ? ',msg.isspace())
print('É printavel ? ',msg.isprintable())
print('É minúsculo ? ',msg.islower())
print('É um identificador válido ? ',msg.isidentifier())
print('É um dígito ? ',msg.isdigit())
print('É decimal ? ',msg.isdecimal())
print('É numérico ? ',msg.isnumeric())